/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ocacjava2_6pm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
/**
 *
 * @author LENOVO
 */
public class p1adrgn extends javax.swing.JFrame {
    public String emailPattern="^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public int checkUsername=0;

    /**
     * Creates new form p1adrgn
     */
    String firstname;
    String lastname;
    String gender;
    String emptype;
    String mobileno;
    String username;
    String password;
    static boolean isNumber(String s){
        for(int i=0;i<s.length();i++){
         if(!Character.isDigit(s.charAt(i))){
             return false;
         }   
        }
        return true;
    }
    public static boolean isCharacter(String str){
        for(int i=0;i<str.length();i++){
            if(!(Character.isLetter(str.charAt(i)))){
                return false;
            }
        }
        return true;
    }
    public static boolean checkValidEmail(String str){
    
        int position_of_at= str.indexOf('@');
        int position_of_dot= str.indexOf('.');
        int position_of_space=str.indexOf(' ');
        
        if(position_of_space>=0){
            return false;
        }
        
        if(position_of_at<=0){
            return false;
        }
       if(position_of_dot==0){ 
            return false;
        } 
       if(position_of_dot<position_of_at){ 
            return false;
        } 
        if(position_of_dot==str.length()-1){ 
            return false;
        }
        if(position_of_dot==position_of_at+1){
            return false;
        }
        if (str.indexOf('@' , position_of_at+1)!=-1) {
            return false;  
        }
        if (str.indexOf('.' , position_of_dot+1)!=-1) {
            return false;  
        }
        
        return true;
        
}
    public p1adrgn() {
        initComponents();
        iconLabel.setVisible(false);
        setLocationRelativeTo(null);
        ButtonGroup bg=new ButtonGroup();
        bg.add(b1);
        bg.add(b2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        b1 = new javax.swing.JRadioButton();
        b2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        u1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        c1 = new javax.swing.JCheckBox();
        p1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        cb1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 83, 162, 33));

        t1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        t1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 83, 278, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 134, 153, 33));

        t2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        t2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 134, 278, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Gender");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 185, 153, 37));

        b1.setBackground(new java.awt.Color(0, 0, 255));
        b1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b1.setText("Male");
        jPanel1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 185, 105, -1));

        b2.setBackground(new java.awt.Color(0, 0, 255));
        b2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b2.setText("Female");
        jPanel1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 185, 122, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Mobile No.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 283, 147, 33));

        t3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        t3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 283, 278, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("USERNAME");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 362, 170, 33));

        u1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        u1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        u1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        u1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                u1KeyReleased(evt);
            }
        });
        jPanel1.add(u1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 362, 342, -1));

        jLabel8.setBackground(new java.awt.Color(204, 204, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("PASSWORD");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 413, 170, 33));

        c1.setBackground(new java.awt.Color(153, 153, 255));
        c1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        c1.setText("Show Password");
        c1.setBorder(null);
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel1.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 452, 127, -1));

        p1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        p1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        p1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 413, 342, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ocacjava2_6pm/cloud-upload-icon.png"))); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 124, 42));

        cb1.setBackground(new java.awt.Color(204, 204, 255));
        cb1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select emp. type", "Developer", "Test Engineer", "Project Manager", "Admin" }));
        jPanel1.add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 228, 278, 37));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Emp. Type");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 228, 162, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ocacjava2_6pm/profile.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 161, 201, 116));

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ocacjava2_6pm/no.png"))); // NOI18N
        jPanel1.add(iconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 362, -1, 33));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ocacjava2_6pm/backspace-erase-icon.png"))); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 137, 42));

        jButton5.setBackground(new java.awt.Color(153, 153, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ocacjava2_6pm/chevron-direction-left-round-filled-icon.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 51, 42));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Registration");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ocacjava2_6pm/25134501_6986163 (1).jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 850, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 850, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        p1adwk obj=new p1adwk();
        obj.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        t1.setText("");
        t2.setText("");
        b1.setSelected(false);
        b2.setSelected(false);
        cb1.setSelectedIndex(0);
        t3.setText("");
        u1.setText("");
        p1.setText("");
        c1.setSelected(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        firstname=t1.getText();
        lastname=t2.getText();
        if(b1.isSelected()){
            gender="Male";
        }
        else if(b2.isSelected()){
            gender="Female";
        }
        if(cb1.getSelectedItem().equals("Developer")){
            emptype="Developer";
        }
        else if(cb1.getSelectedItem().equals("Test Engineer")){
            emptype="Test Engineer";
        }
        else if(cb1.getSelectedItem().equals("Project Manager")){
            emptype="Project Manager";
        }
        else if(cb1.getSelectedItem().equals("Admin")){
            emptype="Admin";
        }
        mobileno=t3.getText();
        username=u1.getText();
        password=p1.getText();
        if(t1.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"First name field is required");
        }
        else if(!isCharacter(firstname.trim())){
            JOptionPane.showMessageDialog(this,"Require the firstname in english characters");
        }
        else if(t2.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Last name field is required");
        }
        else if(!isCharacter(lastname.trim())){
            JOptionPane.showMessageDialog(this,"Require the lastname in english characters");
        }
        else if(!(b1.isSelected()) && !(b2.isSelected())){
            JOptionPane.showMessageDialog(null,"Please select your gender");
        }
        else if(cb1.getSelectedItem().equals("Select emp. type")){
            JOptionPane.showMessageDialog(null,"Please select the employee type");
        }
        else if(t3.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Mobile number field is required");
        }
        else if(t3.getText().length()>=11 || t3.getText().length()<=9){
            JOptionPane.showMessageDialog(this,"Enter the phone number of 10 digis");
        }
        else if(!isNumber(t3.getText())){
            JOptionPane.showMessageDialog(this,"Enter the mobile number in integer format");
        }
        else if(u1.getText().trim().equals("") && p1.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter the username and password");
        }
        else if(u1.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Username field is required");
        }
        else if(!checkValidEmail(u1.getText())){
            JOptionPane.showMessageDialog(this,"Please enter a valid email");
        }
        else if(p1.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Password field is required");
        }
        else if(p1.getText().trim().length()<8){
            JOptionPane.showMessageDialog(null,"Password is too short");
        }
        else if(!p1.getText().contains("@")){
            JOptionPane.showMessageDialog(null,"Password field must contain a special character(@)");
        }
        else{
            try{

                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con=DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe","system","25112003");
                String sql="insert into engineers(firstname,lastname,gender,emptype,mobileno,username,password) values(?,?,?,?,?,?,?)";
                PreparedStatement ps=con.prepareStatement(sql);
                ps.setString(1,firstname);
                ps.setString(2,lastname);
                ps.setString(3,gender);
                ps.setString(4,emptype);
                ps.setString(5,mobileno);
                ps.setString(6,username);
                ps.setString(7,password);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this,"Data inserted Successfully");
                p1wledrs obj=new p1wledrs();
                obj.setVisible(true);
                this.setVisible(false);

            }

            catch(Exception e){

            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        if(c1.isSelected()){
            p1.setEchoChar((char)0);
        }
        else{
            p1.setEchoChar('*');
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void u1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_u1KeyReleased
        username=u1.getText();
        if(!(username.trim().equals("")) && username.matches(emailPattern)){
            iconLabel.setVisible(true);
            iconLabel.setIcon(new ImageIcon("src\\ocacjava2_6pm\\yes.png"));
            iconLabel.setText("");
            checkUsername=0;
            try{
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con=DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe","system","25112003");
                String sql="select username from engineers where username=?";
                PreparedStatement ps=con.prepareStatement(sql);
                ps.setString(1,username);
                ResultSet rs=ps.executeQuery();
                while(rs.next()){
                    checkUsername=1;
                    iconLabel.setIcon(new ImageIcon("src\\ocacjava2_6pm\\no.png"));
                    iconLabel.setText("");
                }
            }
            catch(Exception e){

            }
        }
        else{
            iconLabel.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_u1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(p1adrgn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(p1adrgn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(p1adrgn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(p1adrgn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new p1adrgn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton b1;
    private javax.swing.JRadioButton b2;
    private javax.swing.JCheckBox c1;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField p1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField u1;
    // End of variables declaration//GEN-END:variables
}
