/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ocacjava2_6pm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class p1fgpsd extends javax.swing.JFrame {

    /**
     * Creates new form p1fgpsd
     */
    String username;
    String password1;
    String password2;
    String password3;
    public p1fgpsd() {
        initComponents();
        ub.setEnabled(false);
        p2.setEditable(false);
        p3.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        u1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ub = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        p2 = new javax.swing.JPasswordField();
        c2 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        c3 = new javax.swing.JCheckBox();
        p3 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 223, 136, 18));

        u1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel1.add(u1, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 253, 340, 36));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setText("New Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 322, 185, 37));

        ub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ocacjava2_6pm/history-line-icon.png"))); // NOI18N
        ub.setText("UPDATE");
        ub.setBorder(null);
        ub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubActionPerformed(evt);
            }
        });
        jPanel1.add(ub, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 130, 35));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ocacjava2_6pm/backspace-erase-icon.png"))); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, 111, 35));

        p2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jPanel1.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 312, 286, 36));

        c2.setBackground(new java.awt.Color(153, 153, 255));
        c2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        c2.setText("Show Password");
        c2.setBorder(null);
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        jPanel1.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 354, 132, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ocacjava2_6pm/search.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 252, 41, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ocacjava2_6pm/forgot-password-icon.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 136, 134));

        jButton5.setBackground(new java.awt.Color(153, 153, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ocacjava2_6pm/chevron-direction-left-round-filled-icon.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 57, 42));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setText("Confirm Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 411, 185, 41));

        c3.setBackground(new java.awt.Color(153, 153, 255));
        c3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        c3.setText("Show Password");
        c3.setBorder(null);
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        jPanel1.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 458, 132, -1));

        p3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 411, 286, 41));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Forgot Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ocacjava2_6pm/25134501_6986163 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 850, 610));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 850, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
    if(c2.isSelected()){
            p2.setEchoChar((char)0);
        }
        else{
            p2.setEchoChar('*');
        }

// TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        username=u1.getText();
        if(username.trim().equals("")){
                JOptionPane.showMessageDialog(null,"Username can't be blank");
        }
        else{
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection(
               "jdbc:oracle:thin:@localhost:1521:xe","system","25112003");
            String sql="select username from engineers where username=?";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(1,u1.getText());
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                p2.setEditable(true);
                p3.setEditable(true);
                ub.setEnabled(true);
            }
            else{
                JOptionPane.showMessageDialog(this,"Please enter correct username");
            }
            con.close();
        }
        catch(Exception e){
        }   
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        p1wledrs obj=new p1wledrs();
        obj.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubActionPerformed
        username=u1.getText();
        password2=p2.getText();
        password3=p3.getText();
        if(password2.trim().equals("")){
            JOptionPane.showMessageDialog(this,"Enter a new password");
        }
        else if(password3.trim().equals("")){
            JOptionPane.showMessageDialog(this,"Enter the confirm password");
        }
        else if(password2.trim().equals("") && password3.trim().equals("")){
            JOptionPane.showMessageDialog(this,"Password field is required");
        }
        else if(password2.trim().length()<8){
            JOptionPane.showMessageDialog(this,"New password is too short");
        }
        else if(!password2.contains("@")){
                JOptionPane.showMessageDialog(null,"New password must contain a special character(@)");
        }
        else if(!password2.equals(password3)){
            JOptionPane.showMessageDialog(this,"New and confirm password are different");
        }        
        else{
        try{           
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection(
            "jdbc:oracle:thin:@localhost:1521:xe","system","25112003");
            String sql="update engineers set password=? where username=?";
            PreparedStatement ps=con.prepareStatement(sql);
            ps.setString(2,username);
            ps.setString(1,password2);
            int rowsUpdate=ps.executeUpdate();
            if(rowsUpdate>0){
                JOptionPane.showMessageDialog(this,"Password changed Successfully");
            }
            else{
            JOptionPane.showMessageDialog(this,"No records found for given username");
            }
            ps.close();
            con.close();
        }
        catch(Exception e){
            e.printStackTrace();
        }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ubActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        u1.setText("");
        p2.setText("");
        p3.setText("");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        if(c3.isSelected()){
            p3.setEchoChar((char)0);
        }
        else{
            p3.setEchoChar('*');
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(p1fgpsd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(p1fgpsd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(p1fgpsd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(p1fgpsd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new p1fgpsd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField p2;
    private javax.swing.JPasswordField p3;
    private javax.swing.JTextField u1;
    private javax.swing.JButton ub;
    // End of variables declaration//GEN-END:variables
}
