/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ocacjava2_6pm;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
/**
 *
 * @author LENOVO
 */
public class p1prf extends javax.swing.JFrame {

    /**
     * Creates new form p1prf
     */
    String firstname;
    String lastname;
    String gender;
    String emptype;
    String mobileno;
    String username;
    String password;
    static boolean isNumber(String s){
        for(int i=0;i<s.length();i++){
         if(!Character.isDigit(s.charAt(i))){
             return false;
         }   
        }
        return true;
    }
    public static boolean isCharacter(String str){
        for(int i=0;i<str.length();i++){
            if(!(Character.isLetter(str.charAt(i)))){
                return false;
            }
        }
        return true;
    }
    public static boolean checkValidEmail(String str){
    
        int position_of_at= str.indexOf('@');
        int position_of_dot= str.indexOf('.');
        int position_of_space=str.indexOf(' ');
        
        if(position_of_space>=0){
            return false;
        }
        
        if(position_of_at<=0){
            return false;
        }
       if(position_of_dot==0){ 
            return false;
        } 
       if(position_of_dot<position_of_at){ 
            return false;
        } 
        if(position_of_dot==str.length()-1){ 
            return false;
        }
        if(position_of_dot==position_of_at+1){
            return false;
        }
        if (str.indexOf('@' , position_of_at+1)!=-1) {
            return false;  
        }
        if (str.indexOf('.' , position_of_dot+1)!=-1) {
            return false;  
        }
        
        return true;
        
}
    public p1prf() {
        initComponents();
        t1.setVisible(false);
        t1.setEditable(false);
        t2.setVisible(false);
        t2.setEditable(false);
        cb2.setVisible(false);
        cb2.setEditable(false);
        cb1.setVisible(false);
        cb1.setEditable(false);
        t3.setVisible(false);
        t3.setEditable(false);
        jButton4.setEnabled(false);
        jButton1.setEnabled(false);
        jButton6.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        u1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        c1 = new javax.swing.JCheckBox();
        p1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        cb1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        cb2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 213, 162, 33));

        t1.setBackground(new java.awt.Color(153, 153, 255));
        t1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        t1.setBorder(null);
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 213, 261, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 269, 145, 33));

        t2.setBackground(new java.awt.Color(153, 153, 255));
        t2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        t2.setBorder(null);
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 269, 261, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Gender");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 320, 145, 37));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Mobile No.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 428, 147, 33));

        t3.setBackground(new java.awt.Color(153, 153, 255));
        t3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        t3.setBorder(null);
        jPanel1.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 428, 261, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("USERNAME");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 83, 170, 33));

        u1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        u1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        u1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        u1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                u1KeyReleased(evt);
            }
        });
        jPanel1.add(u1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 83, 270, -1));

        jLabel8.setBackground(new java.awt.Color(204, 204, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("PASSWORD");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 133, 170, 33));

        c1.setBackground(new java.awt.Color(153, 153, 255));
        c1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        c1.setText("Show Password");
        c1.setBorder(null);
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel1.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 172, 131, -1));

        p1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        p1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        p1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 133, 270, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ocacjava2_6pm/cloud-upload-icon.png"))); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 510, 124, 42));

        cb1.setBackground(new java.awt.Color(0, 153, 153));
        cb1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select emp. type", "Developer", "Test Engineer", "Project Manager", "Admin" }));
        jPanel1.add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 370, 261, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Emp. Type");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 368, 162, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ocacjava2_6pm/user-male-icon.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 60, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ocacjava2_6pm/backspace-erase-icon.png"))); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 510, 137, 42));

        jButton5.setBackground(new java.awt.Color(153, 153, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ocacjava2_6pm/chevron-direction-left-round-filled-icon.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 53, 44));

        cb2.setBackground(new java.awt.Color(0, 153, 153));
        cb2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select gender", "Male", "Female" }));
        jPanel1.add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 320, 261, 37));

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ocacjava2_6pm/search-icon.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 102, 41, 37));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ocacjava2_6pm/history-line-icon.png"))); // NOI18N
        jButton4.setText("UPDATE");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 509, 144, 45));

        jButton6.setBackground(new java.awt.Color(153, 153, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Update Password");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 172, 121, 17));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Profile");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ocacjava2_6pm/25134501_6986163 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void u1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_u1KeyReleased

        // TODO add your handling code here:
    }//GEN-LAST:event_u1KeyReleased

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        if(c1.isSelected()){
            p1.setEchoChar((char)0);
        }
        else{
            p1.setEchoChar('*');
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String username=u1.getText();
        String firstname=t1.getText();
        String lastname=t2.getText();
        String gender=cb2.getSelectedItem().toString();
        String emptype=cb1.getSelectedItem().toString();
        String mobileno=t3.getText();
        if(username.trim().equals("")){
            JOptionPane.showMessageDialog(this,"Username is required");
        }
        else if(!checkValidEmail(username)){
                JOptionPane.showMessageDialog(this,"Please enter a valid username");
        }
        else if(firstname.trim().equals("")){
            JOptionPane.showMessageDialog(this,"Firstname is required");
        }
        else if(!isCharacter(firstname.trim())){
                JOptionPane.showMessageDialog(this,"Require the firstname in english characters");
        }
        else if(lastname.trim().equals("")){
            JOptionPane.showMessageDialog(this,"Lastname is required");
        }
        else if(!isCharacter(lastname.trim())){
                JOptionPane.showMessageDialog(this,"Require the lastname in english characters");
        }
        else if(gender.equals("Select gender")){
            JOptionPane.showMessageDialog(this,"Please select your gender");
        }
        else if(emptype.equals("Select emp. type")){
            JOptionPane.showMessageDialog(this,"Please select the employee type");
        }
        else if(mobileno.trim().equals("")){
            JOptionPane.showMessageDialog(this,"Mobile number is required");
        }
        else if(mobileno.length()>=11 || mobileno.length()<=9){
                JOptionPane.showMessageDialog(this,"Enter the phone number of 10 digis");
        }
        else if(!isNumber(mobileno)){
                JOptionPane.showMessageDialog(this,"Enter the mobile number in integer format");
        }
        else{
            try{
               Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection(
              "jdbc:oracle:thin:@localhost:1521:xe","system","25112003");
            String sql="update engineers set firstname=?,lastname=?,gender=?,emptype=?,mobileno=? where username=?";
            PreparedStatement ps=con.prepareStatement(sql); 
            ps.setString(1,firstname);
            ps.setString(2,lastname);
            ps.setString(3,gender);
            ps.setString(4,emptype);
            ps.setString(5,mobileno);
            ps.setString(6,username);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"User data updated  Successfully");
            }
            catch(Exception e){
                
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        t1.setText("");
        t2.setText("");
        cb1.setSelectedItem("Select emp. type");
        cb2.setSelectedItem("Select gender");
        t3.setText("");
        u1.setText("");
        p1.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        p1wledrs obj=new p1wledrs();
        obj.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(u1.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Username can't be blank");
        }
        else if(p1.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null,"Password can't be blank");
        }
        else{
            try{
                username=u1.getText();
                password=p1.getText();
                t1.setVisible(true);
                t2.setVisible(true);
                cb1.setVisible(true);
                cb2.setVisible(true);
                t3.setVisible(true);
                jButton4.setEnabled(true);
                jButton1.setEnabled(true);
                jButton6.setVisible(true);
                Class.forName("oracle.jdbc.driver.OracleDriver");
                Connection con=DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe","system","25112003");
                String sql="select * from engineers where username=? and password=?";
                PreparedStatement ps=con.prepareStatement(sql);
                ps.setString(1,username);
                ps.setString(2,password);
                ResultSet rs=ps.executeQuery();
                if(rs.next()){
                    t1.setText(rs.getString("firstname"));
                    t2.setText(rs.getString("lastname"));
                    cb2.setSelectedItem(rs.getString(3));
                    cb1.setSelectedItem(rs.getString(4));
                    t3.setText(rs.getString(5));
                }
                else{
                    JOptionPane.showMessageDialog(this,"Please enter correct username and password");
                }
                con.close();
            }
            catch(Exception e){
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        t1.setBackground(Color.white);
        t2.setBackground(Color.white);
        cb1.setBackground(Color.white);
        cb2.setBackground(Color.white);
        t3.setBackground(Color.white);
        t1.setEditable(true);
        t2.setEditable(true);
        cb1.setEditable(true);
        cb2.setEditable(true);
        t3.setEditable(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        p1udpsd obj=new p1udpsd();
        obj.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(p1prf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(p1prf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(p1prf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(p1prf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new p1prf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox c1;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField p1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField u1;
    // End of variables declaration//GEN-END:variables
}
